{
  "hash": "1060670b0a9a6305e36e0113b029580e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Daily Exercise 05\"\nauthor: \"Libby Prince\"\ndate: \"2025-02-23\"\nformat: html\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n# Install and load the palmerpenguins package\nif (!require(palmerpenguins)) install.packages(\"palmerpenguins\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: palmerpenguins\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Examine the dataset using the `?Help` page\nhead(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 8\n  species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n  <fct>   <fct>              <dbl>         <dbl>             <int>       <int>\n1 Adelie  Torgersen           39.1          18.7               181        3750\n2 Adelie  Torgersen           39.5          17.4               186        3800\n3 Adelie  Torgersen           40.3          18                 195        3250\n4 Adelie  Torgersen           NA            NA                  NA          NA\n5 Adelie  Torgersen           36.7          19.3               193        3450\n6 Adelie  Torgersen           39.3          20.6               190        3650\n# ℹ 2 more variables: sex <fct>, year <int>\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2. What is the class of the penguins dataset?\nclass(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"tbl_df\"     \"tbl\"        \"data.frame\"\n```\n\n\n:::\n:::\n\n\n\nThe class of the penguins dataset is data.frame\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 3. What is the structure of the penguins dataset?\nstr(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [344 × 8] (S3: tbl_df/tbl/data.frame)\n $ species          : Factor w/ 3 levels \"Adelie\",\"Chinstrap\",..: 1 1 1 1 1 1 1 1 1 1 ...\n $ island           : Factor w/ 3 levels \"Biscoe\",\"Dream\",..: 3 3 3 3 3 3 3 3 3 3 ...\n $ bill_length_mm   : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...\n $ bill_depth_mm    : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...\n $ flipper_length_mm: int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...\n $ body_mass_g      : int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...\n $ sex              : Factor w/ 2 levels \"female\",\"male\": 2 1 1 NA 1 2 1 2 NA NA ...\n $ year             : int [1:344] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...\n```\n\n\n:::\n:::\n\n\n\nThere are 344 rows and 8 columns, including variables like species, island, bill length, bill depth, flipper length, body mass, and sex.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 4. What are the dimensions of the penguins dataset?\ndim(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 344   8\n```\n\n\n:::\n:::\n\n\n\nThe dataset has 344 rows and 8 columns.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 5. What are the column names of the penguins dataset?\ncolnames(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"species\"           \"island\"            \"bill_length_mm\"   \n[4] \"bill_depth_mm\"     \"flipper_length_mm\" \"body_mass_g\"      \n[7] \"sex\"               \"year\"             \n```\n\n\n:::\n:::\n\n\n\nThe column names are species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, and sex.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 6. What type of data is `flipper_length_mm` and `Island`?\ntypeof(penguins$flipper_length_mm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"integer\"\n```\n\n\n:::\n\n```{.r .cell-code}\ntypeof(penguins$island)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"integer\"\n```\n\n\n:::\n:::\n\n\n\nThe flipper_length_mm has numerical data and the island column contains text data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 7. What is the mean flipper length of the penguins?\nmean(penguins$flipper_length_mm, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 200.9152\n```\n\n\n:::\n:::\n\n\n\nThe mean flipper length is approximately 200.9 mm.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 8. What is the standard deviation of flipper length in the penguins?\nsd(penguins$flipper_length_mm, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 14.06171\n```\n\n\n:::\n:::\n\n\n\nThe standard deviation of flipper length is approximately 14.1 mm.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 9. What is the median body mass of the penguins?\nmedian(penguins$body_mass_g, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4050\n```\n\n\n:::\n:::\n\n\n\nThe median body mass of the penguins is approximately 4200 g.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 10. What is the Island of the 100th penguin?\npenguins$island[100]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] Dream\nLevels: Biscoe Dream Torgersen\n```\n\n\n:::\n:::\n\n\n\nThe island of the 100th penguin is Biscoe Dream Torgersen\n",
    "supporting": [
      "daily05_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}